apiVersion: v1
kind: Service
metadata:
  name: movie-api-service
  labels:
    env: prod
    owner: arlekinside
spec:
  selector:
    project: movie-api
  type: LoadBalancer
  ports:
    - name: app-listener
      protocol: TCP
      port: 8000
      targetPort: 8000